# Please see the full example under examples/docker-compose.example.yml

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=$DB_ROOT_PASSWD
      - MARIADB_DATABASE=$DB_NAME
      - MARIADB_USER=$DB_USER
      - MARIADB_PASSWORD=$DB_PASSWD
    ports:
      - $DB_PORT:3306

  valkey:
    image: valkey/valkey:8
    container_name: valkey
    restart: unless-stopped
    ports:
      - $REDIS_PORT:6379
    env_file:
      - .env

  postgresql:
    image: docker.io/library/postgres:16-alpine
    container_name: postgresql
    restart: unless-stopped
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    ports:
      - 5432:5432
    env_file:
      - .env

  authentik_server:
    image: ghcr.io/goauthentik/server:2024.10.4
    container_name: authentik_server
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: valkey
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: $POSTGRES_USER
      AUTHENTIK_POSTGRESQL__NAME: $POSTGRES_DB
      AUTHENTIK_POSTGRESQL__PASSWORD: $POSTGRES_PASSWORD
      AUTHENTIK_SECRET_KEY: $AUTHENTIK_SECRET_KEY
    volumes:
      - authentik_media:/media
      - authentik_templates:/templates
    env_file:
      - .env
    ports:
      - 9000:9000
      - 9443:9443
    depends_on:
      - postgresql
      - valkey

  authentik_worker:
    image: ghcr.io/goauthentik/server:2024.10.4
    container_name: authentik_worker
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: valkey
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: $POSTGRES_USER
      AUTHENTIK_POSTGRESQL__NAME: $POSTGRES_DB
      AUTHENTIK_POSTGRESQL__PASSWORD: $POSTGRES_PASSWORD
      AUTHENTIK_SECRET_KEY: $AUTHENTIK_SECRET_KEY
    volumes:
      - authentik_media:/media
      - authentik_templates:/templates
    env_file:
      - .env
    depends_on:
      - postgresql
      - valkey

volumes:
  postgres_db:
  authentik_media:
  authentik_templates:
