# Please see the full example under examples/docker-compose.example.yml

services:
  romm-mariadb-dev:
    image: mariadb:11.3.2
    container_name: romm-mariadb-dev
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=$DB_ROOT_PASSWD
      - MARIADB_DATABASE=$DB_NAME
      - MARIADB_USER=$DB_USER
      - MARIADB_PASSWORD=$DB_PASSWD
    ports:
      - $DB_PORT:3306

  romm-valkey-dev:
    image: valkey/valkey:8
    container_name: romm-valkey-dev
    restart: unless-stopped
    ports:
      - $REDIS_PORT:6379
    env_file:
      - .env
