version: '3'
services:
  romm:
    image: 'zurdi15/romm:latest'
    container_name: romm
    environment:
      - DB_HOST=romm_db
      - DB_PORT=3306
      - DB_USER=romm-user
      - DB_PASSWD=change-me
      - CLIENT_ID=<IGDB client id>
      - CLIENT_SECRET=<IGDB client secret>
      - STEAMGRIDDB_API_KEY=WIP
    volumes:
      - '/path/to/library:/library'
    ports:
      - '80:80'
    depends_on:
      - romm_db
    restart: "unless-stopped"

  romm_db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: romm_db
    environment:
      - MYSQL_ROOT_PASSWORD=RootPasswordChangeMe
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD=change-me
    volumes:
      - ./config:/config
    ports:
      - 3306:3306
    restart: "unless-stopped"
