version: '3'
services:
  romm:
    image: 'zurdi15/romm:latest'
    container_name: romm
    environment:
      - ROMM_DB_DRIVER="mariadb" # This variable can be set as: mariadb | sqlite. If it is not defined, sqlite will be the database by default
      - DB_HOST=romm_db # Only if ROMM_DB_DRIVER='mariadb'
      - DB_PORT=3306 # Only if ROMM_DB_DRIVER='mariadb'
      - DB_USER=romm-user # Only if ROMM_DB_DRIVER='mariadb'
      - DB_PASSWD=change-me # Only if ROMM_DB_DRIVER='mariadb'
      - CLIENT_ID=<IGDB client id>
      - CLIENT_SECRET=<IGDB client secret>
      - STEAMGRIDDB_API_KEY=WIP
    volumes:
      - '/path/to/library:/library'
    ports:
      - '80:80'
    depends_on:
      - romm_db
    restart: "unless-stopped"

  # Only if ROMM_DB_DRIVER='mariadb'
  romm_db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: romm_db
    environment:
      - MYSQL_ROOT_PASSWORD=RootPasswordChangeMe
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD=change-me
    volumes:
      - ./config:/config
    ports:
      - 3306:3306
    restart: "unless-stopped"
