# This config file is compatible with Batocera or Retrobat-based set-ups
# Rename this file to `config.yml`, copy it to a `config` folder, and mount that folder as per the docker-compose.example.yml
# Only uncomment the lines you want to use/modify, or add new ones where needed
exclude:
  platforms: []
  roms:
    multi_file:
      names: []
      parts:
        extensions: []
        names: []
    single_file:
      extensions: []
      names: []
filesystem: {}
system:
  platforms:
    3do: 3do
    3ds: 3ds
    archimedes: acorn-archimedes
    amstradcpc: acpc
    advision: adventure-vision
    amiga1200: amiga
    amiga4000: amiga
    amiga500: amiga
    amigacd32: amiga-cd32
    amigacdtv: amiga-cd32
    apfm1000: apf
    apple2gs: apple2gs
    apple2: appleii
    atomiswave: arcade
    fbneo: arcade
    mame: arcade
    model2: arcade
    model3: arcade
    naomi: arcade
    naomi2: arcade
    triforce: arcade
    arcadia: arcadia-2001
    arduboy: arduboy
    astrocade: astrocade
    atari2600: atari2600
    atari5200: atari5200
    atari7800: atari7800
    atari800: atari8bit
    jaguarcd: atari-jaguar-cd
    atarist: atarti-st
    atom: atom
    bbcmicro: bbcmicro
    c128: c128
    c64: c64
    camplynx: camputers-lynx
    pv1000: casio-pv-1000
    adam: colecoadam
    colecovision: colecovision
    pet: cpet
    cplus4: c-plus-4
    crvision: creativision
    dreamcast: dc
    dos: dos
    scv: epoch-super-cassette-vision
    channelf: fairchild-channel-f
    fds: fds
    fm7: fm-7
    fmtowns: fm-towns
    gamate: gamate
    gamecom: game-dot-com
    gamegear: gamegear
    gameandwatch: g-and-w
    gb: gb
    gb2players: gb
    gba: gba
    gba2players: gba
    gbc: gbc
    gbc2players: gbc
    sgb: gbc
    megadrive: genesis-slash-megadrive
    megadrive-msu: genesis-slash-megadrive
    gp32: gp32
    lcdgames: handheld-electronic-lcd
    intellivision: intellivision
    jaguar: jaguar
    lynx: lynx
    megaduck: mega-duck-slash-cougar-boy
    msx1: msx
    msx2: msx2
    msx2+: msx2
    n64: n64
    nds: nds
    neogeo: neogeoaes
    neogeocd: neo-geo-cd
    ngp: neo-geo-pocket
    ngpc: neo-geo-pocket-color
    nes: nes
    gamecube: ngc
    n64dd: nintendo-64dd
    oricatmos: oric
    pc88: pc-8800-series
    pc98: pc-9800-series
    pcfx: pc-fx
    cdi: philips-cd-i
    pokemini: pokemon-mini
    psx: ps
    ps2: ps2
    ps3: ps3
    psp: psp
    psvita: psvita
    samcoupe: sam-coupe
    satellaview: satellaview
    saturn: saturn
    sega32x: sega-32x
    segacd: segacd
    mastersystem: sega-master-system
    sg1000: sg1000
    x68000: sharp-x68000
    zx81: sinclair-zx81
    snes: snes
    snes-msu: snes
    spectravideo: spectravideo
    supracan: super-acan
    supergrafx: supergrafx
    supervision: supervision
    switch: switch
    thomson: thomson-mo5
    ti99: ti-99
    tutor: tomy-tutor
    coco: trs-80-color-computer
    pcengine: turbografx16--1
    pcenginecd: turbografx-16-slash-pc-engine-cd
    vectrex: vectrex
    c20: vic-20
    virtualboy: virtualboy
    vsmile: vsmile
    wii: wii
    wiiu: wiiu
    windows: win
    wswan: wonderswan
    wswanc: wonderswan-color
    x1: x1
    xbox: xbox
    xbox360: xbox360
    zmachine: z-machine
    zxspectrum: zxs
  versions: {}
