version: '3'
volumes:
  mysql_data:
services:
  romm:
    image: zurdi15/romm:latest
    container_name: romm
    environment:
      - ROMM_DB_DRIVER=mariadb # mariadb | sqlite (defaults to sqlite)
      - DB_HOST=mariadb # [Optional]
      - DB_PORT=3306 # [Optional]
      - DB_USER=romm-user # [Optional]
      - DB_NAME=romm # [Optional] Should match the MYSQL_DATABASE value in the mariadb container
      - DB_PASSWD=<database password> # [Optional]
      - REDIS_HOST=redis # [Optional] Enables running long tasks (full rescans) in the background
      - REDIS_PORT=6379 # [Optional]
      - CLIENT_ID=<IGDB client id> # [Optional] Required to fetch metadata from IGDB
      - CLIENT_SECRET=<IGDB client secret> # [Optional] 
      - STEAMGRIDDB_API_KEY=<SteamGridDB api key> # [Optional] Only needed if you want to use SteamGridDB as a source for covers
      - ROMM_AUTH_ENABLED=true # [Optional] Will enable user management and require authentication to access the interface (default to false)
      - ROMM_AUTH_USERNAME=admin # [Optional] Username for default admin user
      - ROMM_AUTH_PASSWORD=<admin password> # [Optional] Password for default admin user (defaults to admin)
      - ROMM_AUTH_SECRET_KEY=<secret key> # [Optional] Used to encrypt user passwords, generate one with `openssl rand -hex 32`
    volumes:
      - '/path/to/library:/romm/library'
      - '/path/to/resources:/romm/resources' # [Optional] Path where roms metadata (covers) are stored
      - '/path/to/config.yml:/romm/config.yml' # [Optional] Path where config is stored
      - '/path/to/database:/romm/database' # [Optional] Only needed if ROMM_DB_DRIVER=sqlite or ROMM_DB_DRIVER not exists 
      - '/path/to/logs:/romm/logs' # [Optional] Path where RomM logs are stored
    ports:
      - 80:80
    depends_on:
      - romm_db
    restart: "unless-stopped"

  # [Optional] Only needed if ROMM_DB_DRIVER=mariadb
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=RootPasswordChangeMe
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD=change-me
    volumes:
      - mysql_data:/var/lib/mysql # Can also be mounted locally if preferred
    ports:
      - 3306:3306
    restart: "unless-stopped"

  # [Optional] Experimental support for Redis backend
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
