version: '3'
volumes:
  mysql_data:
services:
  romm:
    image: zurdi15/romm:latest
    container_name: romm
    environment:
      - ROMM_DB_DRIVER=mariadb # This variable can be set as: mariadb | sqlite. If it is not defined, sqlite will be the database by default
      - DB_HOST=romm_db # Only if ROMM_DB_DRIVER='mariadb'
      - DB_PORT=3306 # Only if ROMM_DB_DRIVER='mariadb'
      - DB_USER=romm-user # Only if ROMM_DB_DRIVER='mariadb'
      - DB_NAME=romm # Only if ROMM_DB_DRIVER='mariadb'. Can be optionally changed, and should match the MYSQL_DATABASE value in the mariadb container.
      - DB_PASSWD=change-me # Only if ROMM_DB_DRIVER='mariadb'
      - CLIENT_ID=<IGDB client id>
      - CLIENT_SECRET=<IGDB client secret>
      - STEAMGRIDDB_API_KEY=<SteamGridDB api key>
    volumes:
      - '/path/to/library:/romm/library'
      - '/path/to/resources:/romm/resources'
      - '/path/to/config.yml:/romm/config.yml'
      - '/path/to/database:/romm/database' # Only if ROMM_DB_DRIVER='sqlite' or ROMM_DB_DRIVER not exists 
    ports:
      - 80:80
    depends_on:
      - romm_db
    restart: "unless-stopped"

  # Only if ROMM_DB_DRIVER='mariadb'
  romm_db:
    image: mariadb:latest
    container_name: romm_db
    environment:
      - MYSQL_ROOT_PASSWORD=RootPasswordChangeMe
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD=change-me
    volumes:
      - mysql_data:/var/lib/mysql # Can also be mounted locally if preferred
    ports:
      - 3306:3306
    restart: "unless-stopped"
