version: "3"

volumes:
  mysql_data:
  romm_resources:

services:
  romm:
    image: zurdi15/romm:latest
    container_name: romm
    restart: unless-stopped
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=romm # Should match MYSQL_DATABASE in mariadb
      - DB_USER=romm-user # Should match MYSQL_USER in mariadb
      - DB_PASSWD= # Should match MYSQL_PASSWORD in mariadb
      - IGDB_CLIENT_ID= # Generate an ID and SECRET in IGDB
      - IGDB_CLIENT_SECRET= # https://api-docs.igdb.com/#account-creation
      - MOBYGAMES_API_KEY= # https://www.mobygames.com/info/api/
      - ROMM_AUTH_SECRET_KEY= # Generate a key with `openssl rand -hex 32`
      - ROMM_AUTH_USERNAME=admin
      - ROMM_AUTH_PASSWORD= # default: admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - romm_resources:/romm/resources" # Resources fetched from IGDB (covers, screenshots, etc.)
      - "/path/to/library:/romm/library" # Your game library
      - "/path/to/assets:/romm/assets" # Uploaded saves, states, etc.
      - "/path/to/config:/romm/config" # [Optional] Path where config.yml is stored
      - "/path/to/logs:/romm/logs" # [Optional] Path where logs are stored
    ports:
      - 80:8080
    depends_on:
      - mariadb
      - redis

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD= # Use a unique, secure password
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD=
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
