version: '3'
volumes:
  mysql_data:
services:
  romm:
    image: zurdi15/romm:latest
    container_name: romm
    environment:
      - ROMM_DB_DRIVER=mariadb # This variable can be set as: mariadb | sqlite. If it is not defined, sqlite will be the database by default
      - DB_HOST=mariadb # [Optional] Only needed if ROMM_DB_DRIVER=mariadb
      - DB_PORT=3306 # [Optional] Only needed if ROMM_DB_DRIVER=mariadb
      - DB_USER=romm-user # [Optional] Only needed if ROMM_DB_DRIVER=mariadb
      - DB_NAME=romm # [Optional] Only needed if ROMM_DB_DRIVER=mariadb. Can be optionally changed, and should match the MYSQL_DATABASE value in the mariadb container.
      - DB_PASSWD=<database password> # [Optional] Only needed if ROMM_DB_DRIVER=mariadb
      # - REDIS_HOST=redis # [Optional][Experimental] Redis enables workers to run long tasks, like full library rescans, without having to wait on the main thread. Can be used with an already existent redis container
      # - REDIS_PORT=6379 # [Optional][Experimental]
      - CLIENT_ID=<IGDB client id>
      - CLIENT_SECRET=<IGDB client secret>
      - STEAMGRIDDB_API_KEY=<SteamGridDB api key> # [Optional]
    volumes:
      - '/path/to/library:/romm/library'
      - '/path/to/resources:/romm/resources' # [Optional] Path where roms metadata (covers) are stored
      - '/path/to/config.yml:/romm/config.yml' # [Optional] Path where config is stored
      - '/path/to/database:/romm/database' # [Optional] Only needed if ROMM_DB_DRIVER=sqlite or ROMM_DB_DRIVER not exists 
      - '/path/to/logs:/romm/logs' # [Optional] Path where RomM logs are stored
    ports:
      - 80:80
    depends_on:
      - romm_db
    restart: "unless-stopped"

  # [Optional] Only needed if ROMM_DB_DRIVER=mariadb
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=RootPasswordChangeMe
      - MYSQL_DATABASE=romm
      - MYSQL_USER=romm-user
      - MYSQL_PASSWORD=change-me
    volumes:
      - mysql_data:/var/lib/mysql # Can also be mounted locally if preferred
    ports:
      - 3306:3306
    restart: "unless-stopped"

  # [Optional][Experimental]
  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   restart: unless-stopped
  #   ports:
  #     - 6379:6379
