name: build romm image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'romm version'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set environment variables
        run: echo "GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        shell: bash
        run: ./.github/scripts/build.sh
        env:
          VERSION: ${{ inputs.version }}