name: build romm image

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          VERSION=dev-0.13
          docker buildx build --push\
            --tag zurdi15/romm:latest --tag zurdi15/romm:${VERSION}\
            --platform linux/amd64,linux/arm/v7,linux/arm64 . --file ./docker/Dockerfile